version: '3.5'

services:
  sbt_env:
    build:
      context: .
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        USER: ${USER}
    user: ${USER_ID}:${GROUP_ID}
    container_name: <container_name>
    ports:
      - "8080:8080"
    volumes:
      - ${CUR_DIR}:${HOME}/app
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - $SSH_AUTH_SOCK:/ssh-agent
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    working_dir: ${HOME}/app
    tty: true
